site_name: translate-md
site_description: Python client to translate markdown files from english to spanish.
site_url: https://plaguss.github.io/translate-md
use_directory_urls: true

theme:
  name: "material"
  palette: 
    - scheme: default
      primary: amber
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - scheme: slate
      primary: amber
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - content.code.annotate 
    - search.suggest
    - search.highlight
    - content.tabs.link
  language: en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - attr_list
  - md_in_html

repo_name: plaguss/translate-md
repo_url: https://github.com/plaguss/translate-md
edit_uri: ""

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src/translate_md]
          rendering:
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            heading_level: 2
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true

nav:
    - Intro: index.md
    - Usage: usage.md
    - API:
        - api/client.md
        - api/markdown.md        